DROP TABLE Employee CASCADE CONSTRAINTS;
DROP TABLE Department CASCADE CONSTRAINTS;
DROP TABLE Branch CASCADE CONSTRAINTS;
DROP TABLE Company CASCADE CONSTRAINTS;

DROP TABLE Customer CASCADE CONSTRAINTS;
DROP TABLE Supplier CASCADE CONSTRAINTS;
DROP TABLE Equipment CASCADE CONSTRAINTS;
DROP TABLE Machine CASCADE CONSTRAINTS;

DROP TABLE Product CASCADE CONSTRAINTS;
DROP TABLE Orders CASCADE CONSTRAINTS;
DROP TABLE Jobsheet CASCADE CONSTRAINTS;
DROP TABLE Payment CASCADE CONSTRAINTS;

DROP TABLE Invoice CASCADE CONSTRAINTS;
DROP TABLE Cashbill CASCADE CONSTRAINTS;
DROP TABLE Transaction CASCADE CONSTRAINTS;
DROP TABLE Receipt CASCADE CONSTRAINTS;

/* --------------- explosion --------------- */
DROP TABLE OrdersProduct CASCADE CONSTRAINTS;
DROP TABLE OrdersEquipment CASCADE CONSTRAINTS;
DROP TABLE OrdersMachine CASCADE CONSTRAINTS;
DROP TABLE ProductMachine CASCADE CONSTRAINTS;
DROP TABLE CustomerBranch CASCADE CONSTRAINTS;

DROP TABLE CustomerEmployee CASCADE CONSTRAINTS;
DROP TABLE EmployeeDepartment CASCADE CONSTRAINTS;
DROP TABLE EmployeeBranch CASCADE CONSTRAINTS;
DROP TABLE MachineEquipment CASCADE CONSTRAINTS;